// Golden conformance: fixtures generated by edge-analyst/scripts/gen-fixtures.mjs, with expected
// outputs computed by running the reference implementation (src/blocklist.js) itself. A failure
// here means the port drifted from the format owner — fix the port, never the fixture. This is
// the .NET twin of camada-core/test/conformance.test.ts, case for case.
using System.Text.Json;
using Camada.Snapshot;

namespace Camada.Tests;

public static class Conformance
{
    public static readonly JsonElement Cases = Fixtures.ReadJson("blk3/cases.json");
    public static readonly JsonElement Cases5 = Fixtures.ReadJson("blk5/cases.json").GetProperty("v5");

    public static Matcher MatcherOf(string name, string d = "blk3") =>
        new(Parser.ParseSnapshot(Fixtures.ReadBin($"{d}/{name}.bin"), Fixtures.ReadJson($"{d}/{name}.meta.json")));

    public static IEnumerable<JsonElement> List(JsonElement arr) => arr.EnumerateArray();

    /// <summary>A v5 case's `headers` is a map with already lower-cased keys — the request as the tap sees
    /// it. It becomes the header(name) getter §D3 defines, exactly as the reference harness does.</summary>
    public static MatchInput AsInput(JsonElement c, bool withHeaders = true)
    {
        var i = c.GetProperty("input");
        Dictionary<string, string>? headers = null;
        if (withHeaders && i.TryGetProperty("headers", out var h) && h.ValueKind == JsonValueKind.Object)
        {
            headers = h.EnumerateObject().ToDictionary(p => p.Name, p => p.Value.GetString()!);
        }
        return new MatchInput
        {
            Ip = Str(i, "ip"),
            Asn = i.TryGetProperty("asn", out var a) && a.ValueKind == JsonValueKind.Number ? a.GetInt64() : null,
            Country = Str(i, "country"),
            Tlsx = Str(i, "tlsx"),
            Path = Str(i, "path"),
            Ua = Str(i, "ua"),
            Header = headers == null ? null : n => headers.GetValueOrDefault(n),
        };
    }

    private static string? Str(JsonElement o, string name) =>
        o.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.String ? v.GetString() : null;

    private static bool Bool(JsonElement o, string name) => o.TryGetProperty(name, out var v) && v.ValueKind == JsonValueKind.True;

    // the reference reports "nothing matched" as reason null; the port leaves it null too
    public static (bool Block, bool Challenge, bool Allowed, string? Reason) Outcome(MatchResult r) => (r.Block, r.Challenge, r.Allowed, r.Reason);

    public static (bool Block, bool Challenge, bool Allowed, string? Reason) Expect(JsonElement c)
    {
        var e = c.GetProperty("expect");
        return (Bool(e, "block"), Bool(e, "challenge"), Bool(e, "allowed"), Str(e, "reason"));
    }

    public static (bool Block, bool Challenge, bool Allowed, string? Reason, bool Warn, string? Action, string? Rule) Outcome5(MatchResult r) =>
        (r.Block, r.Challenge, r.Allowed, r.Reason, r.Warn, r.Action, r.Rule);

    public static (bool Block, bool Challenge, bool Allowed, string? Reason, bool Warn, string? Action, string? Rule) Expect5(JsonElement c)
    {
        var e = c.GetProperty("expect");
        return (Bool(e, "block"), Bool(e, "challenge"), Bool(e, "allowed"), Str(e, "reason"), Bool(e, "warn"), Str(e, "action"), Str(e, "rule"));
    }

    public static string Label(JsonElement c) => c.GetProperty("input").GetRawText();
}

public class TestV3V4
{
    [Theory]
    [InlineData("v3")]
    [InlineData("v4")]
    public void Basic(string version)
    {
        var m = Conformance.MatcherOf($"{version}-basic");
        var cases = Conformance.List(Conformance.Cases.GetProperty(version).GetProperty("basic")).ToList();
        Assert.Equal(60, cases.Count);
        foreach (var c in cases)
        {
            Assert.True(Conformance.Expect(c) == Conformance.Outcome(m.Match(Conformance.AsInput(c))), Conformance.Label(c));
        }
    }

    [Theory]
    [InlineData("v3")]
    [InlineData("v4")]
    public void Empty(string version)
    {
        var m = Conformance.MatcherOf($"{version}-empty");
        var cases = Conformance.List(Conformance.Cases.GetProperty(version).GetProperty("empty")).ToList();
        Assert.Equal(2, cases.Count);
        foreach (var c in cases)
        {
            Assert.True(Conformance.Expect(c) == Conformance.Outcome(m.Match(Conformance.AsInput(c))), Conformance.Label(c));
        }
    }
}

public class TestV4Outcomes
{
    [Fact]
    public void NeverTwoOutcomeFlags()
    {
        var m = Conformance.MatcherOf("v4-basic");
        var v4 = Conformance.Cases.GetProperty("v4");
        foreach (var c in Conformance.List(v4.GetProperty("basic")).Concat(Conformance.List(v4.GetProperty("empty"))))
        {
            var r = m.Match(Conformance.AsInput(c));
            Assert.True((r.Allowed ? 1 : 0) + (r.Block ? 1 : 0) + (r.Challenge ? 1 : 0) <= 1);
        }
    }

    [Fact]
    public void V3ContainerCannotExpressAllowOrChallenge()
    {
        var v3 = Conformance.MatcherOf("v3-basic");
        var pairs = Conformance.List(Conformance.Cases.GetProperty("v4").GetProperty("basic"))
            .Zip(Conformance.List(Conformance.Cases.GetProperty("v3").GetProperty("basic"))).ToList();
        var diverged = pairs.Where(p => Conformance.Expect(p.First) != Conformance.Expect(p.Second)).ToList();
        Assert.NotEmpty(diverged);   // the fixtures must actually exercise the new sections
        foreach (var (v4c, v3c) in diverged)
        {
            Assert.Equal(Conformance.Expect(v3c), Conformance.Outcome(v3.Match(Conformance.AsInput(v4c))));
        }
    }
}

public class TestV5
{
    private static IEnumerable<JsonElement> Rules => Conformance.List(Conformance.Cases5.GetProperty("rules"));
    private static IEnumerable<JsonElement> Empty => Conformance.List(Conformance.Cases5.GetProperty("empty"));

    [Fact]
    public void RulesCases()
    {
        var m = Conformance.MatcherOf("v5-rules", "blk5");
        Assert.Equal(96, Rules.Count());
        foreach (var c in Rules)
        {
            Assert.True(Conformance.Expect5(c) == Conformance.Outcome5(m.Match(Conformance.AsInput(c))), Conformance.Label(c));
        }
    }

    [Fact]
    public void EmptyCases()
    {
        var m = Conformance.MatcherOf("v5-empty", "blk5");
        Assert.Equal(2, Empty.Count());
        foreach (var c in Empty)
        {
            Assert.True(Conformance.Expect5(c) == Conformance.Outcome5(m.Match(Conformance.AsInput(c))), Conformance.Label(c));
        }
    }

    [Fact]
    public void NeverTwoOutcomeFlags()
    {
        var m = Conformance.MatcherOf("v5-rules", "blk5");
        foreach (var c in Rules.Concat(Empty))
        {
            var r = m.Match(Conformance.AsInput(c));
            Assert.True((r.Allowed ? 1 : 0) + (r.Block ? 1 : 0) + (r.Challenge ? 1 : 0) + (r.Warn ? 1 : 0) <= 1);
        }
    }

    [Fact]
    public void NamesTheRuleOnlyWhenARuleDecided()
    {
        var m = Conformance.MatcherOf("v5-rules", "blk5");
        foreach (var c in Rules)
        {
            var r = m.Match(Conformance.AsInput(c));
            if (r.Reason == "rule")
            {
                Assert.False(string.IsNullOrEmpty(r.Rule));
                Assert.False(string.IsNullOrEmpty(r.Action));
            }
            else
            {
                Assert.Null(r.Rule);
                Assert.Null(r.Action);
            }
        }
    }

    [Fact]
    public void RulesOverruleTheSidesAV4ContainerCanOnlyRead()
    {
        var v4 = Conformance.MatcherOf("v4-basic");
        var rules = Conformance.MatcherOf("v5-rules", "blk5");
        var diverged = Rules.Where(c => Conformance.Outcome(v4.Match(Conformance.AsInput(c))) != Conformance.Outcome(rules.Match(Conformance.AsInput(c)))).ToList();
        Assert.NotEmpty(diverged);
        foreach (var c in diverged)
        {
            Assert.Equal("rule", c.GetProperty("expect").GetProperty("reason").GetString());
        }
    }

    [Fact]
    public void HeaderCasesDecideThroughTheGetterAlone()
    {
        var m = Conformance.MatcherOf("v5-rules", "blk5");
        var headerCases = Rules.Where(c => c.GetProperty("input").TryGetProperty("headers", out _)).ToList();
        Assert.NotEmpty(headerCases);
        foreach (var c in headerCases)
        {
            Assert.Equal(Conformance.Expect5(c), Conformance.Outcome5(m.Match(Conformance.AsInput(c))));
            var blind = m.Match(Conformance.AsInput(c, withHeaders: false));   // no getter: a header condition can never fire (fail open)
            var expect = c.GetProperty("expect");
            if (expect.GetProperty("reason").ValueKind == JsonValueKind.String && expect.GetProperty("reason").GetString() == "rule")
            {
                Assert.NotEqual(expect.GetProperty("rule").GetString(), blind.Rule);
            }
            else
            {
                Assert.Equal(Conformance.Expect(c).Reason, blind.Reason);
            }
        }
    }
}

public class TestInterleaved
{
    [Fact]
    public void InterleavedMatchersKeepStateApart()
    {
        var a = Conformance.MatcherOf("v4-basic");
        var b = Conformance.MatcherOf("v4-empty");
        for (var i = 0; i < 20; i++)
        {
            Assert.Equal("ip6", a.Match(new MatchInput { Ip = "2001:db8::1" }).Reason);
            Assert.False(b.Match(new MatchInput { Ip = "2001:db8::1" }).Block);
            Assert.False(a.Match(new MatchInput { Ip = "2001:db8::2" }).Block);
        }
    }
}
